name: Upload .whl to pypiserver

on:
  push:
    paths:
      - '**/*.whl'

jobs:
  upload-to-pypiserver:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Upload .whl to pypiserver
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_PACKAGE_DIR: ${{ secrets.SERVER_PACKAGE_DIR }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

        # .whl 파일을 pypiserver로 복사
        scp -o StrictHostKeyChecking=no $(find . -name '*.whl') ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PACKAGE_DIR }}
